:Author: keljdoyle
:Email: keljdoyle@yahoo.com
:Date: 30/09/2018
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
Import the project into your Arduino IDE.


== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 simple_rgb_led                => Arduino sketch folder
  ├── simple_rgb_led.ino       => main Arduino file
  ├── layout.png            => an image of the layout
  ├── pir_info.png          => usage of the PIR sensor
  └── ReadMe.adoc           => this file
....


=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Quantity
| L1 | RGB LED        | 1       
| A1 | Arduino Uno    | 1        
| S1 | PIR Sensor     | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
